on:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repository
      uses: actions/checkout@v2
    - name: Get all missing CloudFormation resources
      run: go run main.go types missing cfn types missing cfn > missing
    - name: Create issue with all missing resources
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          var fs = require('fs');
          if (fs.existsSync('missing')) {
            missing = fs.readFileSync('missing', 'utf8');
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Missing CloudFormation resources',
              body: missing
            })
          }
