on:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out aws-terraform-resource-types
      uses: actions/checkout@v2
      with:
        repository: raskad/aws-terraform-resource-types
    - name: Check out this repository
      uses: actions/checkout@v2
      with:
        path: this
    - name: Get all current Terraform resources
      run: go run main.go > resources
    - name: Filter out resources in scope
      run: |
        while read tfResource; do
            if grep -q $tfResource "this/resources.yaml"; then
                echo [OK] $tfResource
            else
                if grep -q $tfResource "this/resourcesBlacklist.yaml"; then
                    echo [OK] $tfResource
                else
                    echo [MISS] $tfResource
                    echo $tfResource >> missing
                fi
            fi
        done <resources
    - name: Create issue with all missing resources
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          var fs = require('fs');
          if (fs.existsSync('missing')) {
            missing = fs.readFileSync('missing', 'utf8');
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Missing Terraform resources',
              body: missing
            })
          }
